### INSERTING ANIME

POST {{api_anime}} HTTP/1.1
Content-Type: application/json

{
  "english_name": "code geass rebel",
  "japanese_name": "コードギアス反逆のルルーシュR2",
  "release_date": "2012-11-25",
  "romaji_name": "code geas hangyaku lelouch R2",
  "type": "TV"
}


### UPDATE ANIME BY ID

PATCH {{api_anime}}/17 HTTP/1.1
Content-Type: application/json

{
  "english_name": "code geass rebel",
  "japanese_name": "コードギアス反逆のルルーシュR2",
  "release_date": "2012-11-25",
  "romaji_name": "code geas hangyaku lelouch R2",
  "type": "TV"
}


### DELETE ANIME BY ID

DELETE {{api_anime}}/14 HTTP/1.1


### GET ANIME BY ID

GET {{api_anime}}/16 HTTP/1.1
