// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anime.sql

package database

import (
	"context"
	"database/sql"
)

const insertAnime = `-- name: InsertAnime :one
INSERT INTO anime(
	created_at,
	updated_at,
	romaji_name,
	japanese_name,
	english_name,
	type,
	release_date
)
VALUES(NOW(), NOW(), $1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, romaji_name, japanese_name, english_name, type, release_date
`

type InsertAnimeParams struct {
	RomajiName   string
	JapaneseName sql.NullString
	EnglishName  sql.NullString
	Type         sql.NullString
	ReleaseDate  sql.NullTime
}

func (q *Queries) InsertAnime(ctx context.Context, arg InsertAnimeParams) (Anime, error) {
	row := q.db.QueryRowContext(ctx, insertAnime,
		arg.RomajiName,
		arg.JapaneseName,
		arg.EnglishName,
		arg.Type,
		arg.ReleaseDate,
	)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RomajiName,
		&i.JapaneseName,
		&i.EnglishName,
		&i.Type,
		&i.ReleaseDate,
	)
	return i, err
}
