// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Anime struct {
	ID           int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	RomajiName   string
	JapaneseName sql.NullString
	EnglishName  sql.NullString
	Type         sql.NullString
	ReleaseDate  sql.NullTime
}
